# Generated by Django 5.1.6 on 2025-03-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='accommodation',
            field=models.CharField(default='5-star accommodation', max_length=100),
        ),
        migrations.AddField(
            model_name='tour',
            name='food_facilities',
            field=models.CharField(default='Food facilities included', max_length=100),
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='tours/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AddField(
            model_name='tour',
            name='reviews',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='tour',
            name='transportation',
            field=models.CharField(default='Transportation included', max_length=100),
        ),
    ]
