# Generated by Django 5.1.5 on 2025-02-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tour_otp_booking'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tour',
            table='pavanputra_tours',
        ),
    ]
