# Generated by Django 5.1.5 on 2025-02-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_tour_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tour',
            table=None,
        ),
    ]
