# Generated by Django 5.1.6 on 2025-03-11 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_passengers', to='myapp.booking')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tour')),
                ('tour_departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tourdeparture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
