# Generated by Django 5.1.5 on 2025-02-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('city_id', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'City',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_id', models.IntegerField(unique=True)),
                ('state_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'States',
                'managed': False,
            },
        ),
    ]
