# Generated by Django 5.1.6 on 2025-03-11 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_extrapassenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='expiry_time',
        ),
    ]
