# Generated by Django 5.1.6 on 2025-03-11 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_otp_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 2, 26, 42, 177500, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
